name: Nuclei Recon Pipeline

on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y chromium golang jq python3-pip

      - name: Setup Go tools
        run: |
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

          # ProjectDiscovery tools
          go install github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
          go install github.com/projectdiscovery/httpx/cmd/httpx@latest
          go install github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest
          go install github.com/tomnomnom/assetfinder@latest
          

          # URL normalization
          pip3 install uro

      - name: Subdomain Enumeration
        run: |
          DOMAIN=vintedgo.com

          echo "[+] Running subfinder"
          subfinder -d $DOMAIN -all -recursive -silent > subs_subfinder.txt

          echo "[+] Running assetfinder"
          assetfinder --subs-only $DOMAIN > subs_assetfinder.txt

          echo "[+] Merging & deduplicating"
          cat subs_*.txt | sort -u > subs.txt

      - name: Probe live hosts
        run: |
          cat subs.txt | httpx -silent -follow-redirects > alive.txt

      - name: Run Nuclei
        run: |
          nuclei -l alive.txt \
            -severity critical,high,medium \
            -o nuclei_results.txt \
            -c 50 -rl 300 -retries 5 \
            -mhe 50 -bs 50 \
            -stats

      - name: Show Nuclei Results
        if: always()
        run: |
          echo "========== NUCLEI RESULTS =========="
          cat nuclei_results.txt || echo "No findings"
